global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api:3000"]

  - job_name: "classifier"
    static_configs:
      - targets: ["classifier:5000"]
